name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ios:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild clean test -quiet -project TimeLapseBuilder.xcodeproj -scheme TimeLapseBuilder-iOS -destination "platform=iOS Simulator,name=iPhone 11 Pro"

  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild clean test -quiet -project TimeLapseBuilder.xcodeproj -scheme TimeLapseBuilder-macOS
