name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild clean test -project TimeLapseBuilder.xcodeproj -scheme TimeLapseBuilder-iOS -destination "platform=iOS Simulator,name=iPhone 16 Pro"

  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild clean test -project TimeLapseBuilder.xcodeproj -scheme TimeLapseBuilder-macOS
